Repository abhisek247767/PeopleHub-Frontend, pull requests merged in 2025-07, with the labels that each got.

#15 feat: enhance project management with new project form and employee l…
  src/app/employee.service.spec.ts
  src/app/employee.service.ts
  src/app/model/interface/master.ts
  src/app/pages/employee/employee.component.html
  src/app/pages/employee/employee.component.ts
  src/app/pages/project/project.component.html
  src/app/pages/project/project.component.ts
Labels: gssoc25, level 3

#18 Validation Failing at registration solved. Showing incorrect error msg.
  src/app/pages/auth/registration/registration.component.ts
Labels: gssoc25, level 1

#28 #26 + # 27 Dropdown fixes+UI_fixes
  src/app/pages/employee/employee.component.css
  src/app/pages/employee/employee.component.html
  src/app/pages/employee/employee.component.ts
  src/app/service/master.service.ts
Labels: gssoc25, level 1

#29 Origin/development
  src/app/model/interface/master.ts
  src/app/pages/employee/employee.component.html
Labels: gssoc25, level 1

#37 #33 Email Verification and Forgot Password Added
  src/app/app.routes.ts
  src/app/pages/auth/forgot-password/forgot-password.component.css
  src/app/pages/auth/forgot-password/forgot-password.component.html
  src/app/pages/auth/forgot-password/forgot-password.component.ts
  src/app/pages/auth/login/login.component.html
  src/app/pages/auth/login/login.component.ts
  src/app/pages/auth/registration/registration.component.html
  src/app/pages/auth/registration/registration.component.ts
  src/app/pages/auth/reset-password/reset-password.component.css
  src/app/pages/auth/reset-password/reset-password.component.html
  src/app/pages/auth/reset-password/reset-password.component.ts
  src/app/pages/auth/service/auth.service.ts
  src/app/pages/auth/verify-email/verify-email.component.css
  src/app/pages/auth/verify-email/verify-email.component.html
  src/app/pages/auth/verify-email/verify-email.component.ts
Labels: gssoc25

#44 Origin/development
  src/app/app.routes.ts
  src/app/pages/auth/forgot-password/forgot-password.component.css
  src/app/pages/auth/forgot-password/forgot-password.component.html
  src/app/pages/auth/forgot-password/forgot-password.component.ts
  src/app/pages/auth/login/login.component.html
  src/app/pages/auth/login/login.component.ts
  src/app/pages/auth/registration/registration.component.html
  src/app/pages/auth/registration/registration.component.ts
  src/app/pages/auth/reset-password/reset-password.component.css
  src/app/pages/auth/reset-password/reset-password.component.html
  src/app/pages/auth/reset-password/reset-password.component.ts
  src/app/pages/auth/service/auth.service.ts
  src/app/pages/auth/verify-email/verify-email.component.css
  src/app/pages/auth/verify-email/verify-email.component.html
  src/app/pages/auth/verify-email/verify-email.component.ts
Labels: gssoc25, level 3

#45 #22 Fixed Project page ui issue
  src/app/app.routes.ts
  src/app/pages/project/project.component.html
  src/app/pages/project/project.component.ts
Labels: gssoc25, level 2

#56 Dark/light mode toggle[GSSoC25]
  .vscode/settings.json
  src/app/app.routes.ts
  src/app/pages/dashboard/dashboard.component.html
  src/app/pages/dashboard/dashboard.component.ts
  src/app/pages/layout/layout.component.css
  src/app/pages/layout/layout.component.html
  src/app/pages/layout/layout.component.ts
  src/styles.css
Labels: gssoc25
