Repository abhisek247767/PeopleHub-Frontend, pull requests merged in 2025-08, with the labels that each got.

#85 Implement confirmation modal for employee deletion and enhance dark m…
  src/app/pages/employee/employee.component.html
  src/app/pages/employee/employee.component.ts
  src/app/shared/confirm-modal/confirm-modal.component.css
  src/app/shared/confirm-modal/confirm-modal.component.html
  src/app/shared/confirm-modal/confirm-modal.component.spec.ts
  src/app/shared/confirm-modal/confirm-modal.component.ts
  src/assets/css/main.css
Labels: gssoc25, level 2

#92 Revert "Forget password ui modification ISSUE 88"
  src/app/pages/auth/forgot-password/forgot-password.component.css
  src/app/pages/auth/forgot-password/forgot-password.component.html
  src/app/pages/employee/employee.component.html
  src/app/pages/employee/employee.component.ts
  src/app/pages/project/project.component.css
  src/app/pages/project/project.component.html
  src/app/pages/project/project.component.ts
Labels: gssoc25, level 1

#98 Enhanced Dashboard: Employee & Project Stats integrated from Backend API
  src/app/pages/dashboard/dashboard.component.html
  src/app/pages/dashboard/dashboard.component.ts
Labels: gssoc25, level 3

#108 fix(ui): update not-found page with header, footer, and working links
  src/app/pages/not-found/not-found.component.css
  src/app/pages/not-found/not-found.component.html
  src/app/pages/not-found/not-found.component.ts
Labels: good first issue, gssoc25
