Repository abhisek247767/PeopleHub-Frontend, pull requests merged in 2025-09, with the labels that each got.

#114 Add structure.txt file
  structure.txt
Labels: gssoc25, level 1

#124 docs: add problem statement and improve README clarity
  README.md
Labels: good first issue, gssoc25, level 1

#130 Feature: enhance footer with quick links and improved navigation
  src/app/pages/footer/footer.component.css
  src/app/pages/footer/footer.component.html
  src/app/pages/footer/footer.component.ts
  src/app/shared/custom-alert/alert.service.ts
  src/app/shared/custom-alert/custom-alert.component.css
  src/app/shared/custom-alert/custom-alert.component.html
  src/app/shared/custom-alert/custom-alert.component.ts
  src/assets/js/main.js
Labels: gssoc25, level 3

#131 feat: Implement project tree view and fix related API calls
  src/app/pages/project/project.component.html
  src/app/pages/project/project.component.ts
  src/app/project.service.ts
Labels: gssoc25, level 3

#139 Fix issue #138: Make navbar sticky while scrolling
  src/assets/css/main.css
Labels: good first issue, gssoc25, level 1

#145 feat: add role-based login option (Admin & Super-admin support)
  src/app/pages/auth/login/login.component.html
  src/app/pages/auth/login/login.component.ts
  src/app/pages/auth/model/interface/auth.ts
  src/app/pages/layout/layout.component.ts
Labels: gssoc25, level 3
